### ISSUE TITLE
chunk crash

### ISSUE THREAD

**Issue by XeweIs** [Salandora/SophisticatedBackpacks#25]
**Describe the bug**
`---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2024-06-19 20:12:41
Description: Feature placement

java.lang.RuntimeException: We are asking a region for a chunk out of bound
at net.minecraft.class_3233.method_8404(class_3233.java:365)
at net.p3pp3rf1y.sophisticatedbackpacks.common.EntityBackpackAdditionHandler.addBackpack(EntityBackpackAdditionHandler.java:119)
at net.p3pp3rf1y.sophisticatedbackpacks.common.CommonEventHandler.onLivingSpecialSpawn(CommonEventHandler.java:225)
at net.p3pp3rf1y.sophisticatedcore.event.common.MobSpawnEvents.lambda$static$0(MobSpawnEvents.java:15)
at net.minecraft.class_1308.handler$deh000$sophisticatedcore$sophosticatedcore$afterFinalizeSpawn(class_1308.java:8084)
at net.minecraft.class_1308.method_5943(class_1308.java:1083)
at net.minecraft.class_1547.method_5943(class_1547.java:150)
at com.telepathicgrunt.repurposedstructures.world.features.Skeletons.method_13151(Skeletons.java:28)
at net.minecraft.class_3031.method_40163(class_3031.java:165)
at net.minecraft.class_2975.method_12862(class_2975.java:27)
at net.minecraft.class_6796.method_39646(class_6796.java:56)
at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
at net.minecraft.class_6796.method_39648(class_6796.java:55)
at net.minecraft.class_6796.method_39644(class_6796.java:40)
at net.minecraft.class_3776.method_16626(class_3776.java:75)
at net.minecraft.class_3790.method_27236(class_3790.java:89)
at net.minecraft.class_3790.method_14931(class_3790.java:85)
at net.minecraft.class_3449.method_14974(class_3449.java:99)
at net.minecraft.class_2794.method_38265(class_2794.java:429)
at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
at net.minecraft.class_2794.method_12102(class_2794.java:428)
at net.minecraft.class_2806.method_20613(class_2806.java:145)
at net.minecraft.class_2806.method_12154(class_2806.java:292)
at net.minecraft.class_3898.method_17225(class_3898.java:679)
at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
at net.minecraft.class_3898.method_17224(class_3898.java:673)
at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
at net.minecraft.class_3900.method_17634(class_3900.java:62)
at net.minecraft.class_3846.method_16907(class_3846.java:91)
at net.minecraft.class_3846.method_16900(class_3846.java:146)
at net.minecraft.class_3846.run(class_3846.java:102)
at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
at net.minecraft.class_3233.method_8404(class_3233.java:365)
at net.p3pp3rf1y.sophisticatedbackpacks.common.EntityBackpackAdditionHandler.addBackpack(EntityBackpackAdditionHandler.java:119)
at net.p3pp3rf1y.sophisticatedbackpacks.common.CommonEventHandler.onLivingSpecialSpawn(CommonEventHandler.java:225)
at net.p3pp3rf1y.sophisticatedcore.event.common.MobSpawnEvents.lambda$static$0(MobSpawnEvents.java:15)
at net.minecraft.class_1308.handler$deh000$sophisticatedcore$sophosticatedcore$afterFinalizeSpawn(class_1308.java:8084)
at net.minecraft.class_1308.method_5943(class_1308.java:1083)
at net.minecraft.class_1547.method_5943(class_1547.java:150)
at com.telepathicgrunt.repurposedstructures.world.features.Skeletons.method_13151(Skeletons.java:28)
at net.minecraft.class_3031.method_40163(class_3031.java:165)
at net.minecraft.class_2975.method_12862(class_2975.java:27)
at net.minecraft.class_6796.method_39646(class_6796.java:56)
at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
at net.minecraft.class_6796.method_39648(class_6796.java:55)
at net.minecraft.class_6796.method_39644(class_6796.java:40)
at net.minecraft.class_3776.method_16626(class_3776.java:75)
at net.minecraft.class_3790.method_27236(class_3790.java:89)
at net.minecraft.class_3790.method_14931(class_3790.java:85)
at net.minecraft.class_3449.method_14974(class_3449.java:99)
at net.minecraft.class_2794.method_38265(class_2794.java:429)
at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422)
at net.minecraft.class_2794.method_12102(class_2794.java:428)
at net.minecraft.class_2806.method_20613(class_2806.java:145)
at net.minecraft.class_2806.method_12154(class_2806.java:292)
at net.minecraft.class_3898.method_17225(class_3898.java:679)
at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
at net.minecraft.class_3898.method_17224(class_3898.java:673)
at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
at net.minecraft.class_3900.method_17634(class_3900.java:62)
at net.minecraft.class_3846.method_16907(class_3846.java:91)
at net.minecraft.class_3846.method_16900(class_3846.java:146)
at net.minecraft.class_3846.run(class_3846.java:102)
`
I guess it's because of some mob

**To Reproduce**
1. I'm flying around the world
2. A crash occurs at a random moment

**Versions**
1.19.2 fabric

**Comment by Salandora** [comment]
What sophisticated backpack version are you on?

**Comment by XeweIs** [comment]
Last (3.19.5 build97)

**Comment by XeweIs** [comment]
please tell me, is there any way to disable spawn mobs with backpacks?

**Comment by Salandora** [comment]
Please post the full crash-log, not just a truncated one, I need more information.

Also yes you can disable it in the config by setting "entityBackpackAdditions chance" to 0

**Comment by XeweIs** [comment]
[
[crash-2024-06-19_20.12.41-server.txt](https://github.com/user-attachments/files/15917474/crash-2024-06-19_20.12.41-server.txt)
](url)

**Comment by Salandora** [comment]
Okay yeah, now it all makes sense again, the crash log still has build.40 in it which I thought so cause this specific bug was fixed a while ago. (But there is a second incompatibility which will get fixed in the hotfix update).
So as of now you can disable mobs spawning with backpacks and once the hotfix is out you can update to that (do not uodate to build 97 it has a major bug)
