### ISSUE TITLE
[1.21.1] Crash when opening the creative menu with Farmers Delight Refabricated installed

### ISSUE THREAD

**Issue by DJChaos42** [Salandora/SophisticatedBackpacks#65]
**Describe the bug**
The game crashes when opening the creative menu with Farmer's Delight Refabricated installed. This seems to be due to a Porting Lib version difference.

<details>
<summary>Crash Log</summary>

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-11-12 12:08:24
Description: Unexpected error

java.lang.IncompatibleClassChangeError: Conflicting default methods: io/github/fabricators_of_create/porting_lib/core/util/MutableDataComponentHolder.set net/p3pp3rf1y/sophisticatedcore/extensions/component/SophisticatedMutableDataComponentHolder.set
	at knot//net.minecraft.class_1799.set(class_1799.java)
	at knot//net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem.setColors(BackpackItem.java:85)
	at knot//net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem.addCreativeTabItems(BackpackItem.java:99)
	at knot//net.p3pp3rf1y.sophisticatedbackpacks.init.ModItems.lambda$static$48(ModItems.java:240)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at knot//net.p3pp3rf1y.sophisticatedbackpacks.init.ModItems.lambda$static$49(ModItems.java:240)
	at knot//net.minecraft.class_1761.method_47306(class_1761.java:102)
	at knot//net.minecraft.class_7706.method_47338(class_7706.java:2166)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at knot//net.minecraft.class_7706.method_47337(class_7706.java:2166)
	at knot//net.minecraft.class_7706.method_47330(class_7706.java:2177)
	at knot//net.minecraft.class_481.method_60324(class_481.java:245)
	at knot//net.minecraft.class_481.<init>(class_481.java:221)
	at knot//net.minecraft.class_490.method_25426(class_490.java:50)
	at knot//net.minecraft.class_437.method_25423(class_437.java:309)
	at knot//net.minecraft.class_310.method_1507(class_310.java:1143)
	at knot//net.minecraft.class_310.method_1508(class_310.java:2068)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1938)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1246)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.minecraft.class_1799.set(class_1799.java)
	at knot//net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem.setColors(BackpackItem.java:85)
	at knot//net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem.addCreativeTabItems(BackpackItem.java:99)
	at knot//net.p3pp3rf1y.sophisticatedbackpacks.init.ModItems.lambda$static$48(ModItems.java:240)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at knot//net.p3pp3rf1y.sophisticatedbackpacks.init.ModItems.lambda$static$49(ModItems.java:240)
	at knot//net.minecraft.class_1761.method_47306(class_1761.java:102)
	at knot//net.minecraft.class_7706.method_47338(class_7706.java:2166)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at knot//net.minecraft.class_7706.method_47337(class_7706.java:2166)
	at knot//net.minecraft.class_7706.method_47330(class_7706.java:2177)
	at knot//net.minecraft.class_481.method_60324(class_481.java:245)
	at knot//net.minecraft.class_481.<init>(class_481.java:221)
	at knot//net.minecraft.class_490.method_25426(class_490.java:50)
	at knot//net.minecraft.class_437.method_25423(class_437.java:309)
	at knot//net.minecraft.class_310.method_1507(class_310.java:1143)
	at knot//net.minecraft.class_310.method_1508(class_310.java:2068)

-- Uptime --
Details:
	JVM uptime: 14.665s
	Wall uptime: 9.432s
	High-res time: 8.424s
	Client ticks: 143 ticks / 7.150s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2501)
	at knot//net.minecraft.class_310.method_54580(class_310.java:949)
	at knot//net.minecraft.class_310.method_1514(class_310.java:905)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Affected level --
Details:
	All players: 1 total; [class_746['DiscoTechMC'/33, l='ClientLevel', x=-8.50, y=-60.00, z=-9.50]]
	Chunk stats: 961, 513
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 536 game time, 536 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 85

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, farmersdelight, forgeconfigapiport, mm, porting_lib_accessors, porting_lib_asm, porting_lib_attributes, porting_lib_base, porting_lib_blocks, porting_lib_common, porting_lib_conditions, porting_lib_config, porting_lib_core, porting_lib_data, porting_lib_entity, porting_lib_extensions, porting_lib_fluids, porting_lib_gametest, porting_lib_gui_utils, porting_lib_item_abilities, porting_lib_lazy_registration, porting_lib_level_events, porting_lib_loot, porting_lib_model_loader, porting_lib_models, porting_lib_recipe_book_categories, porting_lib_tags, porting_lib_transfer, sophisticatedbackpacks, sophisticatedcore, team_reborn_energy

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.2, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 7797657832 bytes (7436 MiB) / 8589934592 bytes (8192 MiB) up to 12717129728 bytes (12128 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i5-13600K
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: Raptor Lake
	Frequency (GHz): 3.49
	Number of physical packages: 1
	Number of physical CPUs: 14
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 4060 Ti
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 16380.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6094
	Graphics card #1 name: Intel(R) UHD Graphics 770
	Graphics card #1 vendor: Intel Corporation
	Graphics card #1 VRAM (MiB): 2048.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.101.5972
	Memory slot #0 capacity (MiB): 32768.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 32768.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MiB): 75023.25
	Virtual memory used (MiB): 28696.18
	Swap memory total (MiB): 9728.00
	Swap memory used (MiB): 194.58
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 84278.16, total: 952965.56
	Space in storage for workdir (MiB): available: 84278.16, total: 952965.56
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms8192m -Xmx12128m
	Fabric Mods: 
		fabric-api: Fabric API 0.107.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.69+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.17+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.1+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.1+7fd4837519
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.2.0+e49211d819
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.22+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.4.0+0f6c53cd19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.1+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabricloader: Fabric Loader 0.16.9
		farmersdelight: Farmer's Delight 1.21.1-2.2.2+refabricated
			mm: Manningham Mills 2.3
			porting_lib_base: Porting Lib Base 3.1.0-fdrf.4+1.21.1
			porting_lib_config: Porting Lib Config 3.1.0-fdrf.4+1.21.1
				com_electronwill_night-config_core: core 3.8.0
				com_electronwill_night-config_toml: toml 3.8.0
			porting_lib_entity: Porting Lib Entity 3.1.0-fdrf.4+1.21.1
			porting_lib_gui_utils: Porting Lib Gui Utils 3.1.0-fdrf.4+1.21.1
			porting_lib_recipe_book_categories: Porting Lib Recipe Book Categories 3.1.0-fdrf.4+1.21.1
			porting_lib_tags: Porting Lib Tags 3.0
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21.1
		sophisticatedbackpacks: Sophisticated Backpacks 1.21.1-3.20.19.44
			forgeconfigapiport: Forge Config API Port 21.1.1
			porting_lib_extensions: Porting Lib Extensions 3.1.0+1.21.1
				porting_lib_accessors: Porting Lib Accessors 3.1.0+1.21.1
				porting_lib_asm: Porting Lib ASM 3.1.0+1.21.1
				porting_lib_attributes: Porting Lib Attributes 3.1.0+1.21.1
				porting_lib_common: Porting Lib Common 3.1.0+1.21.1
			porting_lib_item_abilities: Porting Lib Item Abilities 3.1.0+1.21.1
				porting_lib_blocks: Porting Lib Blocks 3.1.0+1.21.1
				porting_lib_level_events: Porting Lib Level Events 3.1.0+1.21.1
			porting_lib_loot: Porting Lib Loot 3.1.0+1.21.1
				porting_lib_conditions: Porting Lib Conditions 3.1.0+1.21.1
			porting_lib_model_loader: Porting Lib Model Loader 3.1.0+1.21.1
				porting_lib_core: Porting Lib Core 3.1.0+1.21.1
				porting_lib_gametest: Porting Lib GameTest 3.1.0+1.21.1
			porting_lib_transfer: Porting Lib Transfer 3.1.0+1.21.1
			team_reborn_energy: Energy 4.1.0
		sophisticatedcore: Sophisticated Core 1.21.1-0.6.50.52
			mixinextras: MixinExtras 0.5.0-beta.3
			porting_lib_fluids: Porting Lib Fluids 3.1.0+1.21.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 3.1.0+1.21.1
			porting_lib_models: Porting Lib Models 3.1.0+1.21.1
				porting_lib_data: Porting Lib Data 3.1.0+1.21.1
	Launched Version: 1.21.1
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce RTX 4060 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 560.94, NVIDIA Corporation
	Window size: 1900x1000
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, farmersdelight, forgeconfigapiport, mm, porting_lib_accessors, porting_lib_asm, porting_lib_attributes, porting_lib_base, porting_lib_blocks, porting_lib_common, porting_lib_conditions, porting_lib_config, porting_lib_core, porting_lib_data, porting_lib_entity, porting_lib_extensions, porting_lib_fluids, porting_lib_gametest, porting_lib_gui_utils, porting_lib_item_abilities, porting_lib_lazy_registration, porting_lib_level_events, porting_lib_loot, porting_lib_model_loader, porting_lib_models, porting_lib_recipe_book_categories, porting_lib_tags, porting_lib_transfer, sophisticatedbackpacks (incompatible), sophisticatedcore (incompatible), team_reborn_energy
	Current Language: en_us
	Locale: en_US
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 20x 13th Gen Intel(R) Core(TM) i5-13600K
	Server Running: true
	Player Count: 1 / 8; [class_3222['DiscoTechMC'/33, l='ServerLevel[New World]', x=-8.50, y=-60.00, z=-9.50]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2, farmersdelight, porting_lib_base, porting_lib_gametest, porting_lib_item_abilities, porting_lib_tags, sophisticatedbackpacks (incompatible), sophisticatedcore (incompatible)
	Available Data Packs: bundle, fabric, fabric-convention-tags-v2, farmersdelight, porting_lib_base, porting_lib_gametest, porting_lib_item_abilities, porting_lib_tags, sophisticatedbackpacks (incompatible), sophisticatedcore (incompatible), trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -347596259408126165

</details>

**To Reproduce**
1. Install Sophisticated Backpacks, Farmer's Delight Refabricated, and their dependencies.
2. Open any world and set the game mode to creative mode.
3. Attempt to open the inventory.

**Expected behavior**
Players should be able to open the creative menu with both mods installed.

**Versions**
Fabric API [0.107.0+1.21.1] 
Farmer's Delight Refabricated [1.21.1-2.2.2+refabricated] 
Sophisticated Backpacks [1.21.1-3.20.19.44] 
Sophisticated Core [1.21.1-0.6.50.52]

**Comment by Salandora** [comment]
Ahh thanks for letting me know, the commands in questions should have gotten a prefix before release.
Will be fixed in the next release

**Comment by Demadunk** [comment]
Apologies for submitting a duplicate!

**Comment by Salandora** [comment]
@Demadunk no worries :)
Better submit a duplicate then have it never submitted and therefore never fixed.

**Comment by bellbellslimes** [comment]
If you could release the patch for this sometime soon, that would be very appreciated!! It's unplayable on modpacks with this crash, and I would love to play with it! Please release the fix soon! :)

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
