### ISSUE TITLE
Crashing Local Server

### ISSUE THREAD

**Issue by ual1n** [Salandora/SophisticatedBackpacks#74]
**Describe the bug**
Well, I can load the server normally with the mod, however, when I try to connect within the game, the server crashes.

**To Reproduce**
Copy the following mods to the mods folder of the Client and Server:
- sophisticatedbackpacks
- sophisticatedcore
- indium

**Expected behavior**
It is expected that everything work correctly, but the server crashes when I connect. On the client side it works correctly.

**Screenshots**
I don't have screenshots, but I have the error logs:

`[01:49:19] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/class_746
  at net.p3pp3rf1y.sophisticatedbackpacks.common.CommonEventHandler.sendPlayerSettingsToClient(CommonEventHandler.java:172) ~[sophisticatedbackpacks-1.20.4-3.20.6.41.jar:?]
  at net.p3pp3rf1y.sophisticatedbackpacks.common.CommonEventHandler.onPlayerLoggedIn(CommonEventHandler.java:166) ~[sophisticatedbackpacks-1.20.4-3.20.6.41.jar:?]
  at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$8(ServerLifecycleEvents.java:86) ~[fabric-lifecycle-events-v1-2.3.1+a67ffb5d4f-bab4e00cbf3337ab.jar:?]
  at net.minecraft.class_3324.handler$zmc000$fabric-lifecycle-events-v1$hookOnPlayerConnect(class_3324.java:4014) ~[server-intermediary.jar:?]
  at net.minecraft.class_3324.method_14570(class_3324.java:197) ~[server-intermediary.jar:?]
  at net.minecraft.class_8610.mixinextras$bridge$method_14570$27(class_8610.java) ~[server-intermediary.jar:?]
  at net.minecraft.class_8610.md03bac9$polymer-networking$lambda$polymerNet$prePlayHandshakeHackfest$0$0(class_8610.java:1044) ~[server-intermediary.jar:?]
  at eu.pb4.polymer.networking.impl.EarlyPlayConnectionMagic.lambda$handle$0(EarlyPlayConnectionMagic.java:36) ~[polymer-networking-0.7.7+1.20.4-6b962b699fc0802.jar:?]
  at eu.pb4.polymer.networking.impl.EarlyPlayConnectionMagic.handle(EarlyPlayConnectionMagic.java:39) ~[polymer-networking-0.7.7+1.20.4-6b962b699fc0802.jar:?]
  at net.minecraft.class_8610.wrapOperation$bgg000$polymer-networking$polymerNet$prePlayHandshakeHackfest(class_8610.java:1031) ~[server-intermediary.jar:?]
  at net.minecraft.class_8610.method_52408(class_8610.java:128) ~[server-intermediary.jar:?]
  at net.minecraft.class_8736.method_53043(class_8736.java:20) ~[server-intermediary.jar:?]
  at net.minecraft.class_8736.method_11054(class_8736.java:7) ~[server-intermediary.jar:?]
  at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[server-intermediary.jar:?]
  at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
  at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
  at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
  at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:797) ~[server-intermediary.jar:?]
  at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
  at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
  at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:779) ~[server-intermediary.jar:?]
  at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:773) ~[server-intermediary.jar:?]
  at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
  at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:758) ~[server-intermediary.jar:?]
  at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:687) ~[server-intermediary.jar:?]
  at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
  at java.lang.Thread.run(Thread.java:1575) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
  at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
  at java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[?:?]
  at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?]
  at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
  at java.lang.ClassLoader.loadClass(ClassLoader.java:528) ~[?:?]
  ... 27 more
`

**Versions**
Minecraft: 1.20.4
Fabric Loader: 1.16.9

**Comment by Salandora** [comment]
Found the issue, will fix it and release a new version.

**Comment by Salandora** [comment]
New release is out, this should now be fixed.

**Comment by Salandora** [comment]
Sorry forgot to release the fix, it's out now.
