### ISSUE TITLE
Hopper into backpack crashes game

### ISSUE THREAD

**Issue by OkamiTia** [Salandora/SophisticatedBackpacks#76]
When putting a hopper above a backpack and inserting an item via GUI or dropping it in, game crashes and makes world unuseable until you delete the hopper via other tools 

1. place a backpack
2. put hopper above backpack
3. insert item via GUI or dropping
4. crash

Mods used:
fabric-api-0.108.0+1.21.1.jar
sophisticatedbackpacks-1.21.1-3.20.19.51.jar
sophisticatedcore-1.21.1-0.6.50.61.jar

```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-11-26 13:07:58
Description: Moving resources between storages

java.lang.IllegalStateException: An outer transaction is already active on this thread.
	at knot//net.fabricmc.fabric.impl.transfer.transaction.TransactionManagerImpl.openOuter(TransactionManagerImpl.java:40)
	at knot//net.fabricmc.fabric.api.transfer.v1.transaction.Transaction.openOuter(Transaction.java:85)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.lambda$insertItemInternal$11(InventoryHandler.java:333)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.IInventoryPartHandler$Default.insertItem(IInventoryPartHandler.java:126)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.insertItemInternal(InventoryHandler.java:331)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandlerSlotTracker.insertIntoEmptySlots(InventoryHandlerSlotTracker.java:326)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandlerSlotTracker.insertItemIntoHandler(InventoryHandlerSlotTracker.java:244)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.insert(InventoryHandler.java:467)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.insert(InventoryHandler.java:41)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.CachedFailedInsertInventoryHandler.insert(CachedFailedInsertInventoryHandler.java:80)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.CachedFailedInsertInventoryHandler.insert(CachedFailedInsertInventoryHandler.java:16)
	at knot//net.fabricmc.fabric.api.transfer.v1.storage.StorageUtil.move(StorageUtil.java:97)
	at knot//net.minecraft.class_2614.handler$zod000$fabric-transfer-api-v1$hookInsert(class_2614.java:582)
	at knot//net.minecraft.class_2614.method_11246(class_2614.java:147)
	at knot//net.minecraft.class_2614.method_11243(class_2614.java:120)
	at knot//net.minecraft.class_2614.method_31692(class_2614.java:107)
	at knot//net.minecraft.class_2818$class_5563.method_31703(class_2818.java:691)
	at knot//net.minecraft.class_2818$class_5564.method_31703(class_2818.java:745)
	at knot//net.minecraft.class_1937.method_18471(class_1937.java:488)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:413)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at knot//net.fabricmc.fabric.impl.transfer.transaction.TransactionManagerImpl.openOuter(TransactionManagerImpl.java:40)
	at knot//net.fabricmc.fabric.api.transfer.v1.transaction.Transaction.openOuter(Transaction.java:85)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.lambda$insertItemInternal$11(InventoryHandler.java:333)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.IInventoryPartHandler$Default.insertItem(IInventoryPartHandler.java:126)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.insertItemInternal(InventoryHandler.java:331)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandlerSlotTracker.insertIntoEmptySlots(InventoryHandlerSlotTracker.java:326)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandlerSlotTracker.insertItemIntoHandler(InventoryHandlerSlotTracker.java:244)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.insert(InventoryHandler.java:467)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.insert(InventoryHandler.java:41)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.CachedFailedInsertInventoryHandler.insert(CachedFailedInsertInventoryHandler.java:80)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.CachedFailedInsertInventoryHandler.insert(CachedFailedInsertInventoryHandler.java:16)
	at knot//net.fabricmc.fabric.api.transfer.v1.storage.StorageUtil.move(StorageUtil.java:97)
	at knot//net.minecraft.class_2614.handler$zod000$fabric-transfer-api-v1$hookInsert(class_2614.java:582)
	at knot//net.minecraft.class_2614.method_11246(class_2614.java:147)
	at knot//net.minecraft.class_2614.method_11243(class_2614.java:120)
	at knot//net.minecraft.class_2614.method_31692(class_2614.java:107)
	at knot//net.minecraft.class_2818$class_5563.method_31703(class_2818.java:691)
	at knot//net.minecraft.class_2818$class_5564.method_31703(class_2818.java:745)
	at knot//net.minecraft.class_1937.method_18471(class_1937.java:488)

-- Move details --
Details:
	Input storage: InventoryStorage[net.minecraft.class_2614@1bab7577 (Block{minecraft:hopper}[enabled=true,facing=down], minecraft:overworld@7, -59, 0)]
	Output storage: net.p3pp3rf1y.sophisticatedcore.inventory.CachedFailedInsertInventoryHandler@66fa48eb
	Filter: net.minecraft.class_2614$$Lambda/0x00000008014e6298@7c27cb8
	Max amount: 1
	Transaction: ~~NULL~~
Stacktrace:
	at knot//net.fabricmc.fabric.api.transfer.v1.storage.StorageUtil.move(StorageUtil.java:97)
	at knot//net.minecraft.class_2614.handler$zod000$fabric-transfer-api-v1$hookInsert(class_2614.java:582)
	at knot//net.minecraft.class_2614.method_11246(class_2614.java:147)
	at knot//net.minecraft.class_2614.method_11243(class_2614.java:120)
	at knot//net.minecraft.class_2614.method_31692(class_2614.java:107)
	at knot//net.minecraft.class_2818$class_5563.method_31703(class_2818.java:691)
	at knot//net.minecraft.class_2818$class_5564.method_31703(class_2818.java:745)
	at knot//net.minecraft.class_1937.method_18471(class_1937.java:488)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:413)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Block entity being ticked --
Details:
	Name: minecraft:hopper // net.minecraft.class_2614
	Block: Block{minecraft:hopper}[enabled=true,facing=down]
	Block location: World: (7,-59,0), Section: (at 7,5,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Block: Block{minecraft:hopper}[enabled=true,facing=down]
	Block location: World: (7,-59,0), Section: (at 7,5,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
Stacktrace:
	at knot//net.minecraft.class_2818$class_5563.method_31703(class_2818.java:691)
	at knot//net.minecraft.class_2818$class_5564.method_31703(class_2818.java:745)
	at knot//net.minecraft.class_1937.method_18471(class_1937.java:488)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:413)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- Affected level --
Details:
	All players: 1 total; [class_3222['OkamiTan'/1, l='ServerLevel[New World]', x=7.54, y=-60.00, z=-1.50]]
	Chunk stats: 5625
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 486 game time, 486 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Commands: true
	Level weather: Rain time: 20085 (now: false), thunder time: 63669 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Loaded entity count: 120
Stacktrace:
	at knot//net.minecraft.class_3218.method_8538(class_3218.java:1693)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1024)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:114)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1099577768 bytes (1048 MiB) / 1778384896 bytes (1696 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 8192.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.5599
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 34765.16
	Virtual memory used (MiB): 11409.31
	Swap memory total (MiB): 2048.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): available: 299859.13, total: 953237.75
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 299859.13, total: 953237.75
	Space in storage for io.netty.native.workdir (MiB): available: 299859.13, total: 953237.75
	Space in storage for java.io.tmpdir (MiB): available: 299859.13, total: 953237.75
	Space in storage for workdir (MiB): available: 299859.13, total: 953237.75
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.108.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.70+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.18+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.2+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.2+e60e56d419
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.3.0+8e331c5719
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.23+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.0+01d9a51c19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.2+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabricloader: Fabric Loader 0.16.9
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21.1
		sophisticatedbackpacks: Sophisticated Backpacks 1.21.1-3.20.19.51
			forgeconfigapiport: Forge Config API Port 21.1.1
				com_electronwill_night-config_core: core 3.8.0
				com_electronwill_night-config_toml: toml 3.8.0
			porting_lib_extensions: Porting Lib Extensions 3.1.0+1.21.1
				mm: Manningham Mills 2.3
				porting_lib_accessors: Porting Lib Accessors 3.1.0+1.21.1
				porting_lib_asm: Porting Lib ASM 3.1.0+1.21.1
				porting_lib_attributes: Porting Lib Attributes 3.1.0+1.21.1
				porting_lib_common: Porting Lib Common 3.1.0+1.21.1
			porting_lib_item_abilities: Porting Lib Item Abilities 3.1.0+1.21.1
				porting_lib_blocks: Porting Lib Blocks 3.1.0+1.21.1
				porting_lib_level_events: Porting Lib Level Events 3.1.0+1.21.1
			porting_lib_loot: Porting Lib Loot 3.1.0+1.21.1
				porting_lib_conditions: Porting Lib Conditions 3.1.0+1.21.1
			porting_lib_model_loader: Porting Lib Model Loader 3.1.0+1.21.1
				porting_lib_core: Porting Lib Core 3.1.0+1.21.1
				porting_lib_gametest: Porting Lib GameTest 3.1.0+1.21.1
			porting_lib_transfer: Porting Lib Transfer 3.1.0+1.21.1
			team_reborn_energy: Energy 4.1.0
		sophisticatedcore: Sophisticated Core 1.21.1-0.6.50.61
			mixinextras: MixinExtras 0.5.0-beta.3
			porting_lib_fluids: Porting Lib Fluids 3.1.0+1.21.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 3.1.0+1.21.1
			porting_lib_models: Porting Lib Models 3.1.0+1.21.1
				porting_lib_data: Porting Lib Data 3.1.0+1.21.1
	Server Running: true
	Player Count: 1 / 8; [class_3222['OkamiTan'/1, l='ServerLevel[New World]', x=7.54, y=-60.00, z=-1.50]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2, porting_lib_gametest, porting_lib_item_abilities, sophisticatedbackpacks (incompatible), sophisticatedcore (incompatible)
	Available Data Packs: bundle, fabric, fabric-convention-tags-v2, porting_lib_gametest, porting_lib_item_abilities, sophisticatedbackpacks (incompatible), sophisticatedcore (incompatible), trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -1949161159001904502
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.16.9-1.21.1
```

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
