### ISSUE TITLE
Crashing when using inception upgrade and moving item

### ISSUE THREAD

**Issue by OkamiTia** [Salandora/SophisticatedBackpacks#78]
When adding the inception upgrade and moving my axe, game crashes, but with different error than #72 
World is still useable after crash, but moved Item is deleted

Sadly was unable to reproduce this error but in my survival world

Mods used:
fabric-api-0.108.0+1.21.1.jar
sophisticatedbackpacks-1.21.1-3.20.19.51.jar
sophisticatedcore-1.21.1-0.6.50.61.jar

https://github.com/user-attachments/assets/062b5b7c-7341-465d-901a-3965f9659dca

```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-11-26 13:59:42
Description: Rendering screen

java.lang.IllegalStateException: An outer transaction is already active on this thread.
	at knot//net.fabricmc.fabric.impl.transfer.transaction.TransactionManagerImpl.openOuter(TransactionManagerImpl.java:40)
	at knot//net.fabricmc.fabric.api.transfer.v1.transaction.Transaction.openOuter(Transaction.java:85)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.lambda$insertItemInternal$11(InventoryHandler.java:333)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.IInventoryPartHandler$Default.insertItem(IInventoryPartHandler.java:126)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.insertItemInternal(InventoryHandler.java:331)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandlerSlotTracker.insertIntoEmptySlots(InventoryHandlerSlotTracker.java:326)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandlerSlotTracker.insertItemIntoHandler(InventoryHandlerSlotTracker.java:244)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.insert(InventoryHandler.java:467)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.insert(InventoryHandler.java:41)
	at knot//net.p3pp3rf1y.sophisticatedbackpacks.upgrades.inception.InceptionInventoryHandler.insert(InceptionInventoryHandler.java:102)
	at knot//net.p3pp3rf1y.sophisticatedbackpacks.upgrades.inception.InceptionInventoryHandler.insert(InceptionInventoryHandler.java:21)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.IInventoryHandlerHelper.insertItem(IInventoryHandlerHelper.java:27)
	at knot//net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem.getItemStashable(BackpackItem.java:313)
	at knot//net.p3pp3rf1y.sophisticatedcore.client.ClientEventHandler.getStashResultAndTooltip(ClientEventHandler.java:137)
	at knot//net.p3pp3rf1y.sophisticatedcore.client.ClientEventHandler.getStashResultAndTooltip(ClientEventHandler.java:126)
	at knot//net.p3pp3rf1y.sophisticatedcore.client.ClientEventHandler.onDrawScreen(ClientEventHandler.java:83)
	at knot//net.fabricmc.fabric.impl.client.screen.ScreenEventFactory.lambda$createAfterRenderEvent$4(ScreenEventFactory.java:48)
	at knot//net.minecraft.class_757.wrapOperation$znh000$fabric-screen-api-v1$onRenderScreen(class_757.java:2587)
	at knot//net.minecraft.class_757.method_3192(class_757.java:913)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1285)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//net.fabricmc.fabric.impl.transfer.transaction.TransactionManagerImpl.openOuter(TransactionManagerImpl.java:40)
	at knot//net.fabricmc.fabric.api.transfer.v1.transaction.Transaction.openOuter(Transaction.java:85)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.lambda$insertItemInternal$11(InventoryHandler.java:333)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.IInventoryPartHandler$Default.insertItem(IInventoryPartHandler.java:126)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.insertItemInternal(InventoryHandler.java:331)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandlerSlotTracker.insertIntoEmptySlots(InventoryHandlerSlotTracker.java:326)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandlerSlotTracker.insertItemIntoHandler(InventoryHandlerSlotTracker.java:244)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.insert(InventoryHandler.java:467)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.InventoryHandler.insert(InventoryHandler.java:41)
	at knot//net.p3pp3rf1y.sophisticatedbackpacks.upgrades.inception.InceptionInventoryHandler.insert(InceptionInventoryHandler.java:102)
	at knot//net.p3pp3rf1y.sophisticatedbackpacks.upgrades.inception.InceptionInventoryHandler.insert(InceptionInventoryHandler.java:21)
	at knot//net.p3pp3rf1y.sophisticatedcore.inventory.IInventoryHandlerHelper.insertItem(IInventoryHandlerHelper.java:27)
	at knot//net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem.getItemStashable(BackpackItem.java:313)
	at knot//net.p3pp3rf1y.sophisticatedcore.client.ClientEventHandler.getStashResultAndTooltip(ClientEventHandler.java:137)
	at knot//net.p3pp3rf1y.sophisticatedcore.client.ClientEventHandler.getStashResultAndTooltip(ClientEventHandler.java:126)
	at knot//net.p3pp3rf1y.sophisticatedcore.client.ClientEventHandler.onDrawScreen(ClientEventHandler.java:83)
	at knot//net.fabricmc.fabric.impl.client.screen.ScreenEventFactory.lambda$createAfterRenderEvent$4(ScreenEventFactory.java:48)
	at knot//net.minecraft.class_757.wrapOperation$znh000$fabric-screen-api-v1$onRenderScreen(class_757.java:2587)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_490
	Mouse location: Scaled: (687, 281). Absolute: (2061.000000, 843.000000)
	Screen size: Scaled: (1147, 480). Absolute: (3440, 1440). Scale factor of 3.000000
Stacktrace:
	at knot//net.minecraft.class_757.method_3192(class_757.java:913)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1285)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 245.173s
	Wall uptime: 237.419s
	High-res time: 236.163s
	Client ticks: 4638 ticks / 231.900s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2501)
	at knot//net.minecraft.class_310.method_54580(class_310.java:949)
	at knot//net.minecraft.class_310.method_1514(class_310.java:902)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['OkamiTan'/19, l='ClientLevel', x=-352.39, y=89.00, z=276.37]]
	Chunk stats: 3025, 2125
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,87,-16), Section: (at 0,7,0 in 0,5,-1; chunk contains blocks 0,-64,-16 to 15,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 2730035 game time, 3684833 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 228

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, forgeconfigapiport, mm, porting_lib_accessors, porting_lib_asm, porting_lib_attributes, porting_lib_blocks, porting_lib_common, porting_lib_conditions, porting_lib_core, porting_lib_data, porting_lib_extensions, porting_lib_fluids, porting_lib_gametest, porting_lib_item_abilities, porting_lib_lazy_registration, porting_lib_level_events, porting_lib_loot, porting_lib_model_loader, porting_lib_models, porting_lib_transfer, sophisticatedbackpacks, sophisticatedcore, team_reborn_energy, file/VanillaTweaks_r676934_MC1.21.x.zip, file/Blue Ancient Debris 1.20.zip

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 728521568 bytes (694 MiB) / 2315255808 bytes (2208 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor             
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 2070 SUPER
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 8192.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.5599
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 34765.16
	Virtual memory used (MiB): 13735.74
	Swap memory total (MiB): 2048.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): available: 298961.16, total: 953237.75
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 298961.16, total: 953237.75
	Space in storage for io.netty.native.workdir (MiB): available: 298961.16, total: 953237.75
	Space in storage for java.io.tmpdir (MiB): available: 298961.16, total: 953237.75
	Space in storage for workdir (MiB): available: 298961.16, total: 953237.75
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric-api: Fabric API 0.108.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.70+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.18+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.2+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.2+e60e56d419
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.3.0+8e331c5719
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.23+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.0+01d9a51c19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.3+60c3209b19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.87+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.2+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea21519
		fabricloader: Fabric Loader 0.16.9
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21.1
		sophisticatedbackpacks: Sophisticated Backpacks 1.21.1-3.20.19.51
			forgeconfigapiport: Forge Config API Port 21.1.1
				com_electronwill_night-config_core: core 3.8.0
				com_electronwill_night-config_toml: toml 3.8.0
			porting_lib_extensions: Porting Lib Extensions 3.1.0+1.21.1
				mm: Manningham Mills 2.3
				porting_lib_accessors: Porting Lib Accessors 3.1.0+1.21.1
				porting_lib_asm: Porting Lib ASM 3.1.0+1.21.1
				porting_lib_attributes: Porting Lib Attributes 3.1.0+1.21.1
				porting_lib_common: Porting Lib Common 3.1.0+1.21.1
			porting_lib_item_abilities: Porting Lib Item Abilities 3.1.0+1.21.1
				porting_lib_blocks: Porting Lib Blocks 3.1.0+1.21.1
				porting_lib_level_events: Porting Lib Level Events 3.1.0+1.21.1
			porting_lib_loot: Porting Lib Loot 3.1.0+1.21.1
				porting_lib_conditions: Porting Lib Conditions 3.1.0+1.21.1
			porting_lib_model_loader: Porting Lib Model Loader 3.1.0+1.21.1
			porting_lib_transfer: Porting Lib Transfer 3.1.0+1.21.1
				porting_lib_core: Porting Lib Core 3.1.0+1.21.1
				porting_lib_gametest: Porting Lib GameTest 3.1.0+1.21.1
			team_reborn_energy: Energy 4.1.0
		sophisticatedcore: Sophisticated Core 1.21.1-0.6.50.61
			mixinextras: MixinExtras 0.5.0-beta.3
			porting_lib_fluids: Porting Lib Fluids 3.1.0+1.21.1
			porting_lib_lazy_registration: Porting Lib Lazy Register 3.1.0+1.21.1
			porting_lib_models: Porting Lib Models 3.1.0+1.21.1
				porting_lib_data: Porting Lib Data 3.1.0+1.21.1
	Launched Version: fabric-loader-0.16.9-1.21.1
	Launcher name: minecraft-launcher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 555.99, NVIDIA Corporation
	Window size: 3440x1440
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 24/24 chunks
	Resource Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, forgeconfigapiport, mm, porting_lib_accessors, porting_lib_asm, porting_lib_attributes, porting_lib_blocks, porting_lib_common, porting_lib_conditions, porting_lib_core, porting_lib_data, porting_lib_extensions, porting_lib_fluids, porting_lib_gametest, porting_lib_item_abilities, porting_lib_lazy_registration, porting_lib_level_events, porting_lib_loot, porting_lib_model_loader, porting_lib_models, porting_lib_transfer, sophisticatedbackpacks (incompatible), sophisticatedcore (incompatible), team_reborn_energy, file/VanillaTweaks_r676934_MC1.21.x.zip, file/Blue Ancient Debris 1.20.zip (incompatible)
	Current Language: en_us
	Locale: en_GB
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 16x AMD Ryzen 7 3700X 8-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['OkamiTan'/19, l='ServerLevel[Lets Go]', x=-352.39, y=89.00, z=276.37]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2, porting_lib_gametest, porting_lib_item_abilities, sophisticatedbackpacks (incompatible), sophisticatedcore (incompatible), file/afk display v1.1.9 (MC 1.21-1.21.3).zip, file/armor statues v2.8.14 (MC 1.21-1.21.3).zip, file/armored elytra v2.0.2 (MC 1.21-1.21.3).zip, file/bat membranes v1.0.10 (MC 1.21-1.21.3).zip, file/cauldron concrete v3.0.2 (MC 1.21-1.21.3).zip, file/cauldron mud v1.0.2 (MC 1.21-1.21.3).zip, file/chunk loaders v1.0.10 (MC 1.21-1.21.3).zip, file/classic fishing loot v1.1.9 (MC 1.21-1.21.3).zip, file/coordinates hud v1.2.10 (MC 1.21-1.21.3).zip, file/custom nether portals v2.3.12 (MC 1.21-1.21.3).zip, file/double shulker shells v1.3.9 (MC 1.21-1.21.3).zip, file/dragon drops v1.3.9 (MC 1.21-1.21.3).zip, file/durability ping v1.1.9 (MC 1.21-1.21.3).zip, file/fast leaf decay v2.0.12 (MC 1.21-1.21.3).zip, file/graves v3.0.6 (MC 1.21-1.21.3).zip, file/husks drop sand v1.0.2 (MC 1.21-1.21.3).zip, file/mini blocks v1.0.1 (MC 1.21-1.21.3).zip, file/more effective tools v1.0.3 (MC 1.21-1.21.3).zip, file/more mob heads v2.14.2 (MC 1.21-1.21.3).zip, file/multiplayer sleep v2.6.9 (MC 1.21-1.21.3).zip, file/nether portal coords v1.1.9 (MC 1.21-1.21.3).zip, file/player head drops v1.1.9 (MC 1.21-1.21.3).zip, file/real time clock v1.1.9 (MC 1.21-1.21.3).zip, file/redstone rotation wrench v1.1.10 (MC 1.21-1.21.3).zip, file/silence mobs v1.2.3 (MC 1.21-1.21.3).zip, file/silk touch budding amethyst v1.0.1 (MC 1.21-1.21.3).zip, file/spawning spheres v1.1.9 (MC 1.21-1.21.3).zip, file/spectator conduit power v1.1.9 (MC 1.21-1.21.3).zip, file/spectator night vision v1.1.9 (MC 1.21-1.21.3).zip, file/storm channeling v1.0.1 (MC 1.21-1.21.3).zip, file/terracotta rotation wrench v1.1.10 (MC 1.21-1.21.3).zip, file/timber v2.1.11 (MC 1.21-1.21.3).zip, file/track raw statistics v1.7.5 (MC 1.21-1.21.3).zip, file/track statistics v1.1.11 (MC 1.21-1.21.3).zip, file/unlock all recipes v2.0.10 (MC 1.21-1.21.3).zip, file/villager death messages v1.2.11 (MC 1.21-1.21.3).zip, file/villager workstation highlights v1.1.9 (MC 1.21-1.21.3).zip, file/wandering trader announcements v1.0.2 (MC 1.21-1.21.3).zip, file/xp bottling v1.1.10 (MC 1.21-1.21.3).zip, file/VanillaTweaks_c683103_MC1.21-1.21.3.zip
	Available Data Packs: bundle, fabric, fabric-convention-tags-v2, file/VanillaTweaks_c683103_MC1.21-1.21.3.zip, file/afk display v1.1.9 (MC 1.21-1.21.3).zip, file/armor statues v2.8.14 (MC 1.21-1.21.3).zip, file/armored elytra v2.0.2 (MC 1.21-1.21.3).zip, file/bat membranes v1.0.10 (MC 1.21-1.21.3).zip, file/cauldron concrete v3.0.2 (MC 1.21-1.21.3).zip, file/cauldron mud v1.0.2 (MC 1.21-1.21.3).zip, file/chunk loaders v1.0.10 (MC 1.21-1.21.3).zip, file/classic fishing loot v1.1.9 (MC 1.21-1.21.3).zip, file/coordinates hud v1.2.10 (MC 1.21-1.21.3).zip, file/custom nether portals v2.3.12 (MC 1.21-1.21.3).zip, file/double shulker shells v1.3.9 (MC 1.21-1.21.3).zip, file/dragon drops v1.3.9 (MC 1.21-1.21.3).zip, file/durability ping v1.1.9 (MC 1.21-1.21.3).zip, file/fast leaf decay v2.0.12 (MC 1.21-1.21.3).zip, file/graves v3.0.6 (MC 1.21-1.21.3).zip, file/husks drop sand v1.0.2 (MC 1.21-1.21.3).zip, file/mini blocks v1.0.1 (MC 1.21-1.21.3).zip, file/more effective tools v1.0.3 (MC 1.21-1.21.3).zip, file/more mob heads v2.14.2 (MC 1.21-1.21.3).zip, file/multiplayer sleep v2.6.9 (MC 1.21-1.21.3).zip, file/nether portal coords v1.1.9 (MC 1.21-1.21.3).zip, file/player head drops v1.1.9 (MC 1.21-1.21.3).zip, file/real time clock v1.1.9 (MC 1.21-1.21.3).zip, file/redstone rotation wrench v1.1.10 (MC 1.21-1.21.3).zip, file/silence mobs v1.2.3 (MC 1.21-1.21.3).zip, file/silk touch budding amethyst v1.0.1 (MC 1.21-1.21.3).zip, file/spawning spheres v1.1.9 (MC 1.21-1.21.3).zip, file/spectator conduit power v1.1.9 (MC 1.21-1.21.3).zip, file/spectator night vision v1.1.9 (MC 1.21-1.21.3).zip, file/storm channeling v1.0.1 (MC 1.21-1.21.3).zip, file/terracotta rotation wrench v1.1.10 (MC 1.21-1.21.3).zip, file/timber v2.1.11 (MC 1.21-1.21.3).zip, file/track raw statistics v1.7.5 (MC 1.21-1.21.3).zip, file/track statistics v1.1.11 (MC 1.21-1.21.3).zip, file/unlock all recipes v2.0.10 (MC 1.21-1.21.3).zip, file/villager death messages v1.2.11 (MC 1.21-1.21.3).zip, file/villager workstation highlights v1.1.9 (MC 1.21-1.21.3).zip, file/wandering trader announcements v1.0.2 (MC 1.21-1.21.3).zip, file/xp bottling v1.1.10 (MC 1.21-1.21.3).zip, porting_lib_gametest, porting_lib_item_abilities, sophisticatedbackpacks (incompatible), sophisticatedcore (incompatible), trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 105795169
```

**Comment by Salandora** [comment]
Yeah that should be the exact same issue

**Comment by Salandora** [comment]
New release is out, this should now be fixed.
